spring:
  profiles:
    active: dev
jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 60
  tokenHead: Bearer
logging:
  config: classpath:log4j.xml
mybatis:
  mapper-locations:
  - classpath:mappers/*.xml
  - classpath*:com/**/mapper/*.xml
